7103 - made rd the main tile, covid the secondary tile; afg is now th…
fedspendingtransparency/datalab pull request #1069
Opened 2021-02-11 19:01 UTC by brianpetway

…e main tile in the more analysis section; moved c&u into first place in more analyses and kicked account explorer out

https://federal-spending-transparency.atlassian.net/browse/DA-7103

2021-02-13 21:55 UTC, anjenkin commented on src/pages/index.jsx
> +						href="/rd-in contracting/"
The href prop has a space where there should be a -

2021-02-13 21:56 UTC, anjenkin commented on src/pages/index.jsx
> +
Should this commented out text be removed?

2021-02-13 21:57 UTC, anjenkin requested changes
See comments inline

2021-02-16 19:26 UTC, brianpetway commented on src/pages/index.jsx
> +
I left that there because I'm anticipating some back and forth about the length of the text in that body prop for the secondary tile.  When we changed the tiles a couple of weeks ago we decided to go with the shorter text in the secondary tile, but I left that longer text commented out in case we want to switch it.
I'm fine with removing it now if you want me to, but that was my reasoning.

2021-02-16 21:13 UTC, anjenkin approved these changes

2021-02-16 21:13 UTC, merged