8748 - made the glossary button a component
fedspendingtransparency/datalab pull request #1097
Opened 2021-03-01 16:34 UTC by brianpetway

https://federal-spending-transparency.atlassian.net/browse/DA-8748

2021-03-01 16:37 UTC, anjenkin commented on src/components/glossary/glossary-button/glossary-button.jsx
> +      <button id="afg-floating-glossary-button" tabIndex={-1}>
I think we should try to separate out the CSS that specific to this component into it's own css module.

2021-03-01 16:44 UTC, anjenkin commented on src/components/glossary/glossary.jsx
> +				<GlossaryButton />
This button will have to be outside of the Glossary component when we hide the Glossary on the initial page load. 
 Otherwise it will only be visible after opening the Glossary.  We could add it to the header component though it feels like it would make more sense in the footer.  I think what ever way requires the least refactoring of css makes sense.

2021-03-01 16:44 UTC, anjenkin requested changes
See feedback inline

2021-03-02 16:28 UTC, brianpetway commented
Moved the button to the page header, where the glossary component is; moved the css for the button to the glossary-button dir; the button is functional at this time, but it's still using the d3.select in the glossary.jsx for its click function

2021-03-02 20:18 UTC, anjenkin approved these changes

2021-03-02 20:19 UTC, merged