8843 section 3 toggle
fedspendingtransparency/datalab pull request #1164
Opened 2021-03-29 21:45 UTC by brianpetway

https://federal-spending-transparency.atlassian.net/browse/DA-8843

2021-03-30 16:46 UTC, anjenkin requested changes
When toggled to the COVID side, the line under the title and the dollar amounts font color should change to the COVID purple.

See other comments inline.
![Screen Shot 2021-03-30 at 12 46 24 PM](https://user-images.githubusercontent.com/121010/113025436-f4308400-9155-11eb-8464-81e363da3591.png)

2021-03-30 16:46 UTC, anjenkin commented on src/components/toggle/toggle.jsx
> +		const s = document.getElementById('toggle-switch-' + `${idString}`);
This would be more readable if you use template literal here so it's 

"back tick" toggle-switch-${idString} "back tick"

"back tick" should be the actual back tick symbol

2021-03-30 16:46 UTC, anjenkin commented on src/components/toggle/toggle.jsx
> +			e.target.id === 'toggle-switch-' + `${idString}`
same as above

2021-03-30 16:46 UTC, anjenkin commented on src/components/toggle/toggle.jsx
> +				id={'toggle-label-first-' + `${idString}`}
same as above

2021-03-30 16:46 UTC, anjenkin commented on src/components/toggle/toggle.jsx
> +					id={'toggle-switch-' + `${idString}`}
see above

2021-03-30 16:46 UTC, anjenkin commented on src/components/toggle/toggle.jsx
> +				id={'toggle-label-second-' + `${idString}`}
see above

2021-03-30 22:47 UTC, brianpetway commented
Addressed the issues above. Ready to review again.

2021-03-31 12:42 UTC, anjenkin approved these changes

2021-03-31 12:42 UTC, anjenkin commented
@brianpetway I can merge once the conflicts are resolved.

2021-03-31 15:10 UTC, brianpetway commented
When merging dev in to resolve conflicts, I did a couple of other small things, noted in the commit message.
This defect was addressed:
https://federal-spending-transparency.atlassian.net/browse/DA-8958
Ready to review again.

2021-04-01 14:46 UTC, merged