8849 section 3 copy
fedspendingtransparency/datalab pull request #1183
Opened 2021-04-01 20:47 UTC by brianpetway

https://federal-spending-transparency.atlassian.net/browse/DA-8849

I made this branch from the 8847-section-3-downloads branch bc that component is included in the copy. So ideally 8847 will be merged into qat before this branch.

2021-04-05 20:49 UTC, anjenkin commented on src/components/contracts-grid/contracts-grid.jsx
> +          '5 contracts per category.'}
There's alt text in the MAC for this but I don't think it's necessary since this isn't an image.  Actually Kelli removed this from the MAC - https://data-transparency-bfs.slack.com/archives/CJAD4HQBC/p1617396312181300

2021-04-06 13:10 UTC, anjenkin requested changes
See comment inline

2021-04-06 16:25 UTC, brianpetway commented
Made the latest changes specified by Kelli, and Grace has confirmed that the MAC is now finalized. Ready to review.

2021-04-06 18:28 UTC, anjenkin approved these changes

2021-04-06 18:28 UTC, merged