8931 contracts table truncation
fedspendingtransparency/datalab pull request #1208
Opened 2021-04-09 19:16 UTC by brianpetway

https://federal-spending-transparency.atlassian.net/browse/DA-8931

2021-04-12 17:36 UTC, anjenkin commented on src/components/contracts-table/contracts-table.jsx
> +    if (props.windowWidth < 768) {
We should use the tablet variable here

2021-04-12 17:36 UTC, anjenkin requested changes
looks good. see one comment inline

2021-04-12 19:34 UTC, brianpetway commented on src/components/contracts-table/contracts-table.jsx
> +    if (props.windowWidth < 768) {
But the tablet var is 992 and that isn't the number we want in this case. There isn't a var for 768, this is a special case.

2021-04-12 19:37 UTC, brianpetway commented
Ready to review again.
I also included the fix for this issue in this commit:
https://federal-spending-transparency.atlassian.net/browse/DA-9035

2021-04-12 20:08 UTC, anjenkin commented on src/components/contracts-table/contracts-table.jsx
> +    if (props.windowWidth < 768) {
768 is tablet
992 is desktop

2021-04-12 20:10 UTC, anjenkin commented on src/components/contracts-table/contracts-table.jsx
> +    if (props.windowWidth < 768) {
<img width="193" alt="Screen Shot 2021-04-12 at 4 10 03 PM" src="https://user-images.githubusercontent.com/121010/114455269-8cdcf000-9ba9-11eb-89b4-e406f93ea478.png">

2021-04-12 20:11 UTC, anjenkin commented on src/page-sections/rd-in-contracting/contracts/contracts.jsx
> +			setShowAll(!showAll);
if we're setting state based on the previous state to prevent any side effects we should do setShowAll(prevState => !prevState)

2021-04-12 20:11 UTC, anjenkin commented on src/page-sections/rd-in-contracting/contracts/contracts.jsx
>  		setShowAll(!showAll);
Same issue as above

2021-04-12 20:12 UTC, anjenkin commented on src/page-sections/rd-in-contracting/contracts/contracts.jsx
> +			setShowButtonText('Show All');
this is fine but I'm not sure why we're setting the button text state instead of just basing the text off of the showAll state

2021-04-12 21:02 UTC, brianpetway commented on src/components/contracts-table/contracts-table.jsx
> +    if (props.windowWidth < 768) {
I was looking at the enum in screen-mode.js. I'll change it.

2021-04-12 21:59 UTC, brianpetway commented
Ready to review again

2021-04-13 00:23 UTC, anjenkin approved these changes

2021-04-13 00:24 UTC, merged