9789 - added .module to quick-hits.scss file; changed to h3 heading i…
fedspendingtransparency/datalab pull request #1367
Opened 2021-08-06 15:18 UTC by brianpetway

…n header component; changed font size and weight on 'Share' text in Share component

https://federal-spending-transparency.atlassian.net/browse/DA-9789

2021-08-06 18:16 UTC, anjenkin requested changes
See comments inline

2021-08-06 18:16 UTC, anjenkin commented on src/templates/quick-hits.module.scss
> +.quickHitsContainer {
Side note, scss modules recognizes class names with dashes as camelcase so you didn't have to change the classnames

2021-08-06 18:16 UTC, anjenkin commented on src/components/quick-hits-header/quick-hits-header.module.scss
> +  @include h3-subheading();
For 992px and under the header font size should be 32px (or 2rem).  With this fix, the header font is 40px for 992px and under

2021-08-06 18:37 UTC, brianpetway commented on src/templates/quick-hits.module.scss
> +.quickHitsContainer {
I know, it just bugs me when the same class is spelled differently in different places.

2021-08-06 18:37 UTC, brianpetway commented on src/components/quick-hits-header/quick-hits-header.module.scss
> +  @include h3-subheading();
Changed it. But this means it was correct before doesn't it?

2021-08-06 18:37 UTC, brianpetway commented
Ready to review again.

2021-08-09 13:35 UTC, anjenkin approved these changes

2021-08-09 13:35 UTC, merged