9673 create quick hits template
fedspendingtransparency/datalab pull request #1368
Opened 2021-08-06 21:58 UTC by brianpetway

https://federal-spending-transparency.atlassian.net/browse/DA-9673

I put the new viz component into the template, at the top, just to show it temporarily.

2021-08-09 15:13 UTC, anjenkin requested changes
See comments inline.  Also, we can delete the title, date, and introsentence from the graphql query

export const pageQuery = graphql`
	query BlogPostByPath($path: String!) {
		markdownRemark(frontmatter: { path: { eq: $path } }) {
			html
			frontmatter {
				date(formatString: "MMMM DD, YYYY")
				path
				title
				introSentence
			}
		}
	}
`;

2021-08-09 15:13 UTC, anjenkin commented on static/content/quick-hits/output.md
> +# Header 4 Paragraph Headline, keep to 1 line
this should be a h4 instead of h1 and then left aligned in the css

2021-08-09 15:13 UTC, anjenkin commented on static/content/quick-hits/output.md
> +## **Header 5 callout copy, keep to 2 lines.**
this should be a h5 instead of h2 and then left aligned in the css

2021-08-09 15:13 UTC, anjenkin commented on static/content/quick-hits/output.md
> +# Visualization Title
This should be an h4 and then left aligned in the css

2021-08-09 15:13 UTC, anjenkin commented on static/content/quick-hits/output.md
> +date: 2017-07-12T17:12:33.962Z
we shouldn't need the date here?

2021-08-09 16:06 UTC, brianpetway commented
Changes made. Ready to review again.

2021-08-09 19:49 UTC, anjenkin commented on src/templates/quick-hits.module.scss
> +    text-align: left;
the margin below the h4 should be 25px (24px is fine if we use rems)

2021-08-09 19:50 UTC, anjenkin commented on src/templates/quick-hits.module.scss
> +    text-align: left;
the margin for h5 is too large, i think it should be margin 0

2021-08-09 21:13 UTC, brianpetway commented on src/templates/quick-hits.module.scss
> +    text-align: left;
I also increased the margin top for the h4 to match the mock.

2021-08-09 21:14 UTC, brianpetway commented
Ready to review again, again.

2021-08-10 13:11 UTC, anjenkin approved these changes

2021-08-10 13:11 UTC, merged