9900 - corrected yml vars in copy;
fedspendingtransparency/datalab pull request #1395
Opened 2021-09-07 16:36 UTC by brianpetway

https://federal-spending-transparency.atlassian.net/browse/DA-9900

2021-09-08 19:38 UTC, anjenkin commented on src/page-sections/federal-covid-funding/budget/budget.jsx
> +					Over the last year, as programs have been exhausted, renewed, and closed,
The paragraph "In addition to ..." was removed however it looks like that copy is still in the MAC.  And the yaml variable needs to be changed to taxrelief_trillion.  Not sure where this new paragraph that start with "Over the last year..." came from?

2021-09-08 19:38 UTC, anjenkin requested changes
see inline change requested

2021-09-08 20:25 UTC, brianpetway commented
I put that copy back in. The new copy will go in with the new svg and the new bullet point.

2021-09-09 13:36 UTC, anjenkin approved these changes

2021-09-09 13:36 UTC, merged