8340 - Update footer for About Us release
fedspendingtransparency/datalab pull request #967
Opened 2020-11-16 21:02 UTC by anjenkin

https://federal-spending-transparency.atlassian.net/browse/DA-8229

Please note that the column spacing has been updated in Zeplin.  Also, a screenshot of the page with the grid columns has been attached to the ticket.

2020-11-19 14:30 UTC, mattforjan requested changes
on smaller mobile sizes, the Data Lab logo isn't shrinking with the page
<img width="405" alt="Screen Shot 2020-11-19 at 9 21 55 AM" src="https://user-images.githubusercontent.com/64594352/99679227-b609b200-2a49-11eb-9641-f4fbcc60d659.png">
\+ comments below

2020-11-19 14:30 UTC, mattforjan commented on src/components/footers/page.jsx
> +						<a target="_blank" rel="noopener noreferrer" href="/about">
since this link is going to our about page, shouldn't it open in the same tab?

2020-11-19 14:30 UTC, mattforjan commented on src/components/footers/page.jsx
> +							Community Page today.
in Zeplin, the word "today" wasn't included in the link, just "Community Page"

2020-11-19 14:31 UTC, mattforjan commented on src/components/footers/page.jsx
> +						<a
these links should have `font-weight: normal` according to Zeplin

2020-11-20 16:40 UTC, anjenkin commented
@mattforjan Addressed feedback

2020-11-20 17:47 UTC, mattforjan requested changes
one last comment

2020-11-20 17:47 UTC, mattforjan commented on src/components/footers/page.jsx
> +							Community Page.
meant to say that the mocks do have the word "today" in them, they're just not part of the link
![Screen Shot 2020-11-20 at 12 44 40 PM](https://user-images.githubusercontent.com/64594352/99832202-330e5780-2b2e-11eb-83c5-def29e4771e2.png)

2020-11-23 18:38 UTC, mattforjan approved these changes

2020-11-23 18:38 UTC, merged