[7850] Desktop AFG Sub-nav
fedspendingtransparency/datalab pull request #983
Opened 2020-12-02 19:11 UTC by mattforjan

https://federal-spending-transparency.atlassian.net/browse/DA-7850

Overview page:
<img width="1679" alt="Screen Shot 2020-12-02 at 2 02 18 PM" src="https://user-images.githubusercontent.com/64594352/100918875-0d2a7080-34a7-11eb-900e-b4628675e30d.png">

Specific page:
<img width="1679" alt="Screen Shot 2020-12-02 at 2 02 30 PM" src="https://user-images.githubusercontent.com/64594352/100918894-11ef2480-34a7-11eb-8cee-e2d61c6cca61.png">

2020-12-04 19:47 UTC, anjenkin requested changes
An AC was added to this ticket to make the main nav bar switch to the hamburger menu at < 992px instead of 768px.

Also, when you scroll down, the subnav shouldn't be sticky.  Once you've scrolled past it, it should only appear again on scroll up.  It's up to you if you want to remove the sticky now or wait until https://federal-spending-transparency.atlassian.net/browse/DA-7854

Finally, one of the subpage dividers is darker than the others.

![Screen Shot 2020-12-04 at 2 46 27 PM](https://user-images.githubusercontent.com/121010/101208084-a2f90380-363f-11eb-829a-a1e0defdc24e.png)

2020-12-04 19:47 UTC, anjenkin commented on src/components/afg-nav/afg-nav.jsx
> +        setStickyStyle(window.pageYOffset > 26 && window.innerWidth >= 992 ? { position: 'sticky', top: 50 } : { marginTop });
I think it would be better to use the variable for the screen width 992 here for consistency

2020-12-04 19:47 UTC, anjenkin commented on src/utils/screen-mode.js
> +  if (width < 990) {
I think this good to have as a util though I don't think we can reliably say that mobile is less than 660 for AFG or less than 990 is tablet.  Tablet would need to be 992 to work for the nav bar

2020-12-04 21:03 UTC, mattforjan commented
@anjenkin fixed all the above except the one divider being darker - I'm not seeing that at all no matter the section, page, or screen width. can you double check that and see if you can reproduce it?

2020-12-07 15:35 UTC, anjenkin approved these changes

2020-12-07 15:35 UTC, merged