[8428] Change AFG nav dropdown to single link
fedspendingtransparency/datalab pull request #997
Opened 2020-12-22 16:56 UTC by mattforjan

https://federal-spending-transparency.atlassian.net/browse/DA-8428

2020-12-22 20:40 UTC, anjenkin commented
Works well.

The afg conditions in the sublistTab function can be removed - 


  sublistTab = (e, name) => {
    if (e.key === 'Escape') {
      if (name === 'Analyses') {
        this.handleClick('Analyses');
        document.getElementById('analysesBtn').focus();
      } else if (name === 'Resources') {
        this.handleClick('Resources');
        document.getElementById('resourcesBtn').focus();
      } else if (name === "America's Finance Guide") {
        this.handleClick("America's Finance Guide");
        document.getElementById('afgBtn').focus();
      } else {
        return null;
      }
    }
    if (e.key === 'Tab') {
      if ((document.activeElement.id === 'menu-first-item' && e.shiftKey) || (document.activeElement.id === 'menu-last-item' && !e.shiftKey)) {
        if (name === 'Analyses') {
          this.handleClick('Analyses');
        } else if (name === 'Resources') {
          this.handleClick('Resources');
        } else if (name === "America's Finance Guide") {
          this.handleClick("America's Finance Guide");
        } else {
          return null;
        }
      }
    }
  }

2020-12-22 20:40 UTC, anjenkin requested changes
just one change request

2020-12-28 14:16 UTC, mattforjan commented
@anjenkin fixed

2020-12-29 14:23 UTC, anjenkin approved these changes

2020-12-29 14:23 UTC, merged